# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  message: "Hello World!"

stages:
- stage: Install Node and React
  jobs:
  - job: InstallNode
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: |
          echo message
          npm install
          npm run build
        displayName: 'npm install and build'

  - job: InstallReact
    steps:
        - script: |
            echo message
            npm install react
          displayName: 'npm install react'

- stage: Install ngrok and restify (for Bot Framework)
  jobs:
  - job: Install-ngrok
    steps:
    - script: |
        echo message
        npm install
        npm run build
      displayName: 'npm install and build'
  - job: InstallRestify
    steps:
    - script: |
        echo message
        npm install restify
      displayName: 'npm install restify'