# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

stages:

  variables:
    message: "Hello World!"

  -stage:
  pool:
    vmImage: ubuntu-latest
  jobs:
    -job:
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        echo message
        npm install
        npm run build
      displayName: 'npm install and build'

    - job:
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install react'

      - script: |
          echo message
          npm install react
        displayName: 'npm install react'
    
  -stage:
    pool:
    vmImage: ubuntu-latest
    -job:
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install ngrok'

    - script: |
        echo message
        npm install ngrok
      displayName: 'npm install ngrok'

    - job:
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install restify'

      - script: |
          echo message
          npm install restify
        displayName: 'npm install restify'
